name: GitHub Deploy

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NEW_ENV_VAR_1: ${{ secrets.NEW_ENV_VAR_1 }}  # Update with your new env variable names
  NEW_ENV_VAR_2: ${{ secrets.NEW_ENV_VAR_2 }}
  NEW_ENV_VAR_3: ${{ secrets.NEW_ENV_VAR_3 }}

jobs:

  deploy:
    name: DevMeshConnector
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'

  backend:
    needs: deploy
    if: ${{ needs.deploy.outputs.backend == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Build Backend
        run: |
          cd backend
          npm install
          npm run build

      - name: Deploy Backend
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add backend/build
          git commit -m "Deploy backend"
          git push origin main  # Change to your target branch

  frontend:
    needs: deploy
    if: ${{ needs.deploy.outputs.frontend == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Deploy Frontend
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add frontend/build
          git commit -m "Deploy frontend"
          git push origin main  # Change to your target branch

  deploy-to-gh-pages:
    needs: [backend, frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Deploy Frontend to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: frontend/build  # Path to the built frontend
          target-folder: /  # Deploy to the root of GitHub Pages

      - name: Deploy Backend to GitHub Pages
        run: |
          # If you want to deploy backend artifacts, you can add commands here
          echo "Backend deployment can be handled separately, as GitHub Pages is typically for static sites."