name: Fly Deploy
on: [push]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:

  create-envfile:
    name: Spicy env file
    runs-on: ubuntu-latest
    steps:
      - name: Make envfile
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
  backend:
    needs: deploy
    if: ${{ needs.deploy.outputs.backend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
        working-directory: ./backend
  frontend:
    needs: deploy
    if: ${{ needs.deploy.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy
        working-directory: ./frontend
